# Generated by Django 4.2.1 on 2023-05-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('data', models.DateField(verbose_name='data')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
            ],
        ),
    ]
